version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=1G
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf

  php:
    image: php:8.3-cli
    container_name: php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test_db
    command: bash -c "docker-php-ext-install pdo pdo_mysql && php -S 0.0.0.0:80 -t /var/www/html"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
